config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  before_action :service

  def index
    @markets = @service.markets["data"]
  end

  def show
    @market = @service.get_market(params[:id])
    @vendors = @service.market_vendors(params[:id])
  end

  private
  
  def service
    @service ||= BackendService.new
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :service

  def show
    @vendor = @service.get_vendor(params[:id])
  end

  private
  
  def service
    @service ||= BackendService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<style>
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  table {
    margin-top: 20px;
    width: 70%;
  }
</style>
<div class="container">
  <h1>Markets</h1>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>State</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @markets.each_with_index do |market, index| %>
        <tr class="<%= index.even? ? 'even-row' : 'odd-row' %>">
          <td><%= market["attributes"]["name"] %></td>
          <td><%= market["attributes"]["city"] %></td>
          <td><%= market["attributes"]["state"] %></td>
          <td><%= link_to 'More Info', market_path(market["id"]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/markets/show.html.erb
<h1><%= @market["data"]["attributes"]["name"] %></h1>
<p>Address: <%= @market["data"]["attributes"]["street"] %>, 
<%= @market["data"]["attributes"]["city"] %>, 
<%= @market["data"]["attributes"]["state"] %>, 
<%= @market["data"]["attributes"]["zip"] %></p>

<h2>Vendors</h2>
<ul>
  <% @vendors["data"].each do |vendor| %>
    <li><%= link_to vendor["attributes"]["name"], vendor_path(vendor["id"]) %></li>
  <% end %>
</ul>

app/views/vendors/show.html.erb
<h1><%= @vendor["data"]["attributes"]["name"] %></h1>
<p>Contact Name: <%= @vendor["data"]["attributes"]["contact_name"] %></p>
<p>Contact Phone: <%= @vendor["data"]["attributes"]["contact_phone"] %></p>
<p>Accepts Credit: <%= @vendor["data"]["attributes"]["credit_accepted"] ? "Yes" : "No" %></p>
<p>Description: <%= @vendor["data"]["attributes"]["description"] %></p>